Refresh plugin for August 2023
jenkinsci/google-metadata-plugin pull request #59
Opened 2023-08-29 21:07 UTC by basil

2023-08-29 23:02 UTC, basil commented
Currently blocking https://github.com/jenkinsci/bom/pull/2440

2023-08-30 05:11 UTC, olamy requested changes

2023-08-30 05:11 UTC, olamy commented on Jenkinsfile
> +    [platform: 'windows', jdk: 11],
still java 8 support?
if not maybe worth to add the minimum jdk requirement in the PR title as is this will be in the release notes

2023-08-30 15:08 UTC, basil commented on Jenkinsfile
> +    [platform: 'windows', jdk: 11],
Am I understanding correctly that you are a maintainer of this repository and can therefore edit PR titles?

2023-09-07 16:38 UTC, basil commented
Currently blocking https://github.com/jenkinsci/bom/pull/2440

2023-09-21 09:38 UTC, olamy commented on Jenkinsfile
> +    [platform: 'windows', jdk: 11],
I''m really sorry for the delay and misunderstanding. But as you are the owner of the current work (this PR) I was under the impression you would have been the most appropriate to modify your own work after review from the member of this project's community. I'm not usually modifying work from others.
But so as it looks to take time, I will do it.

2023-09-21 09:40 UTC, olamy commented
I modified the title. I really hope it doesn't modify too much your work with your agreement.

2023-09-21 09:40 UTC, merged

2023-09-21 18:30 UTC, basil commented
Thanks. I generally don't include minimum core version changes in release notes for the plugins I maintain (unless the minimum core version is unusual, like a weekly release or a very recent LTS) because such plugin releases aren't even advertised in the UI to users of older cores. Similarly, a recent core version implies a minimum Java version, and users running older Java versions (and therefore older cores) wouldn't get an advertisement for such a plugin upgrade in the UI, so I generally don't include minimum Java version changes in release notes. I have filed dozens (hundreds?) of PRs without this information in the title and shipped dozens of releases without this information in the release notes, all without any complaints from users or other developers. But I acknowledge that as the plugin maintainer, you should be free to include (or not include) any information you want in the release notes. I hope that this discussion about writing release notes has not been a significant distraction from the comparatively far more laborious task of modernizing the plugin itself.